### ISSUE TITLE
調用外部播放器 直鏈播放 能提供嗎？

### ISSUE THREAD

**Issue by kai456789** [MisakaF0406/MisakaF_Emby#4]
如標題跟附圖 調用MX POT VLC的方式？ 謝謝
![image](https://user-images.githubusercontent.com/720118/197134821-6d9218a9-e4ac-4d07-94c4-551105f36351.png)

**Comment by daoyv** [comment]
找到播放器复制路径，不要有符合“”

**Comment by MisakaF0406** [comment]
https://greasyfork.org/zh-CN/scripts/406811-embylaunchpotplayer

**Comment by MisakaF0406** [comment]
https://greasyfork.org/zh-CN/scripts/406811-embylaunchpotplayer
你可以参考这个脚本，具体使用方式可见如下：
-------------
推荐直接将js脚本部署到emby_server,这样就不需要油猴了: 以linux为例,在/opt/emby-server/system/dashboard-ui目录下新建externalPlayer.js文件,将本脚本内容复制到里面,然后在当前目录下的index.html的 /body上面引入脚本即可 
<script src="./externalPlayer.js" ></script>

**Comment by kai456789** [comment]
> ## https://greasyfork.org/zh-CN/scripts/406811-embylaunchpotplayer
> 你可以参考这个脚本，具体使用方式可见如下：
> 推荐直接将js脚本部署到emby_server,这样就不需要油猴了: 以linux为例,在/opt/emby-server/system/dashboard-ui目录下新建externalPlayer.js文件,将本脚本内容复制到里面,然后在当前目录下的index.html的 /body上面引入脚本即可
> 
> <script src="./externalPlayer.js" ></script>

感謝 好方式 成功了
